global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'  # Ensure this endpoint is exposed in your Spring Boot application
    static_configs:
      - targets: ['host.docker.internal:8080']  # Adjust as necessary for your setup